apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellyfin-credentials
  namespace: jellyfin
spec:
  encryptedData:
    admin-password: AgAcGdRm/+7ssfywEfxkFw3jzQQ6AcEbrlQCcdW7C50dGMajFXJ+Y7CLETxAfl6NiT2e/tqqUPAqVwp1KCQ4DzUTsFv2FDC0pKLSmvRt6V4260wG4cxbf9b71iXzRYliDhjumH90yiySQRbG6xQvyvD7L6ugjgqlxZStjp4INxxOcY/VKtzfbWyZuxrSJinZgZKWItk6yf5cSFO3HgJlqVRZCJcURVmklzoBanNmKE0Ng3U808xo8KVMT0/AUdcP2BuTCBiZYxSpBoCUANyPFr+r28ff1PpsN7WYwa6SQDPvIb8Z6OVpQB2mMq/fzf4l3BmQGAPnt2+ZijuLvigwlPnM+SEIo4gVXPZ/R9PnE4heu8sEZ18n9gvE1/UHkJ7xJqZF2tCPBym0H4AcHGpxduLF7ib+D3On75gSK69/190+g6lC/7wToQJC9CV2WA39n/mVSZgyFgwzKpF7v6TUxT+uAd2BoZFu/bW0eezu+srGtWvDA3nAwN4ynflm29GsJZT2XHOkFAqQ1YWy4STzeA5qB2gvlXPBUcqAdFZRa3YVuVVLRamtk/S2m+6qaOK7GEBiuFiSb8zP1Fij9PQj2lzAqenmbEgFwIbQT2Mevtj6d5VJhp+1B4SOMXP1Jc1CUZxl2ZSAIn/T6ubzd2YbRlPN4R6rF7Cvg2aY8mF0EfSaU2qT5xpi57COSQcb7UbTOYf00w==
  template:
    metadata:
      name: jellyfin-credentials
      namespace: jellyfin
    type: Opaque