apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellyfin-credentials
  namespace: jellyfin
spec:
  encryptedData:
    admin-password: AgAvgQu3TqCvumYKUDAT4+ffYWKMJQ5pdDkLyKDdBK00qk6RYFfz0KePcWoFw249eDSz52p9qpgUp/Y62BhTs7evVpbpqZR4DvyxfiugDO+9Q9iCRs1HjAClajEgOhvLUlFl/G9PAJ6uAgbhqJTioQWg+4xlTxMTVCLbpjQ2SKFWpw7D5Mr18O6p+LHPts+8eE7L+IPaWz2BxnuyDHuoNvoZ1DbPEmBUBprrjzrdoI6jpB1qMJBm0YD51iWUi+7eBqUGLPn8bR/qZog9g1ovE4gZqqd8LUkI6nnqodKDk0LpbFE6+EpIk5xGCGIChqXN1ESUs1J7wQj1MEX7bduQCBIrph6xsyCv1rU2GUaQEEsZursimbPclCwr2g1c0UJMqztNcACPNZZKJXYGAIIZFCtVgGCmKU6cgM8gRT2HIoOpuxISb46NQwZVUlIPNXCa9G67Br97hw043liOEHH4ALru3A0tOsalwT7yX+EykuLC03rHzU9Gr5cKbv1qgHiD+eopCGcKrDs4XGvFlFZS/4TwsA9KRb1yB4g2dmUaKIkkxurjT/QHdGSBqfgRsCFUDK01YToTjEb9JQntNaT0oO+pXGktzBgLkOgfWAKuNzWsNdZ+oYtKB2WALfGQREJOk00nv3qnwIFPncMawjzA6Kj5L5T4iuTgux6fDqA3Zfiqkv4jn8dWwhqR8R+UL6OoNo7Gog==
  template:
    metadata:
      name: jellyfin-credentials
      namespace: jellyfin
    type: Opaque
