apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    # Longhorn Helm chart from official repository
    - repoURL: https://charts.longhorn.io
      targetRevision: 1.11.1
      chart: longhorn
      helm:
        valueFiles:
          - $values/apps/longhorn/values.yaml
    # Git repository containing values.yaml
    - repoURL: https://github.com/denisecodes/k3s-apps
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - Replace=true
