---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: navidrome-spotify
  namespace: navidrome
spec:
  encryptedData:
    client-id: AgAktf5Gxs6pR4grm+GsPEgMoo4upMfbe5ai+ejElUME2HsOPRIpF+7o6TbhQiofhJ30vlzC1nJSsjbtzpC6pwYpWVbd6Qh8kouq2b9m9V9RKQxpR28LWM12k+xvGAI/zN1yXZaz26EIqUgvaU/Gq4Iwsoe26dW3GkF9ydpjNt2oahtOHHeHZllkxNLUwC4QeQB5T/IquTIPzloKW6QTbJDe8N/PII9h9fDCYAPB3FkKhrERQs53LQEOmRFykLXfR0cE7/tUDOexRo3zFF1mdSYn9YTc9sDM5CnMZm3RWSybQj33XFEg5XwyRvChNZUzZtolz+/9PsTNK4RIRL9IHH97lpwrwAG4qvUvmaLoqohv0UR++FjotX4l/57Yj+B9Uxwy8lSxvbyKsH2wVS774Gt7oyD0v/jDwm3ko9UJVIAo3vswbpFy9DwO+eBsYYtR0hiBZZXfSZHP0/3mxHlSKmrSdwNdw9kTZJTwZHIR5wulpjnqg66lwTNrP+EmkJHdcYp3oLXf0xXyim+1hKP5W+r46oWOs7iSpMdjlaSwbdrfUkfh4CmYZrWT4lk57NLCJ35lHzGDWCdelnCx477yJejs0zD7JBIZMencKsH+xYRh5GI+VLnSm2BbzCnJdfzEw5wgFrJVUFA5K7flJG3QRjjjcKsdF0D4V18iiFMgB8i0KLQWYhwyhD3oOogZIvm9sZEbvg0+ohbRNe/aNKtnrmyBfBxtAvgWvw59MGPVH3btKA==
    client-secret: AgCitWx+WkxU3kI4YkX3rmsKL8o7tp5aJb6+AWKvq+uRVe699aeVuoYoRmCh2M9aRqCmMpFpYu0Czga6J9Fc2Wik0NxSijZsixeen9mFD3ryWRwLhPINI8ip5rMjSFRW7076whT/ofEqzt91Jy0bUYChhmCkaX5+knVQNng8oT7UHFjRAshKY1S8A7lQLZmOMEBRcAD+xNns4VYiNQ6xN7Tav6WJ3Exyi6Mk2srEdQJzfILZkt+HpVRyAhphDlFN1XnENRP4dlxxai9kCqq1H5mJk7K27xYnwycK9gqY1Ge+GQ799kgPK55hkyml06CgnUiWAJGx5O87zy+hDRJjdguGFzPKQgS5VdNaouslQ7Ssut9HTQSD4vsXoMvyMa/JQOYuvKYeok9e0JiNdOKKx9wr4dzYta4WaywJkmUbCTukH3gOMwGyBWPkko4QqfGE8xSLyO6BoDHadRwd0b/bQ+htxDtEaOnFOqpm852ADyEpBJHWxT4GmyqufYwTR+UFmbZiXAPvsKQ1KU0nxIuI0Wxqy7lTyMNBJ7/HuGdDhJm4OXX7+hC7nFuMUSCIKLlltcZqv3lODoTjmvS0jOASTtiOjZ6qcfBV5Fq60FQZ3T1/Cnfl179pbNw1lPcW3JX44oPa/c+gWVAg5yvmh0R+j7gCRGH47z2zOy34rgLKc46oyJBxz6lNBruD89oC808pr5gcq+286wQZF+gELdNWJovX9S8Dk8eS3iz3L1jhl+Dr+Q==
  template:
    metadata:
      name: navidrome-spotify
      namespace: navidrome
