---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: navidrome-lastfm
  namespace: navidrome
spec:
  encryptedData:
    ND_LASTFM_APIKEY: AgCMsoxMA/OC7Y1a2Y85QYRybgOvMAyHxadUxQu22fcJQsZU6W7NI0jZAtGqNhT3fAGgEaDE3mYgWo9Iy4ORKdrtZLOYBOuviF9Iy12lqWyvSuzw3P9giBisObZeZcRtCb+ISCkjuASn9VveGk6wHprgPipINVxi9/7c18OUYYTazYfOYl4evgWt+qI+SGIdEF81rN7fXEaUn61DpK/+f/x8HpJzkarsacdU8mcIAiZFvQ/RNXm0tlMHwIGpXyI18ZEvxE5sYz8Ciy3YybQymel+R+OxxzrZPhnFNrYqa+vdJju3OIl/0BVl15AlbX+oTO7Vi9ZTkmVhrjBGjoUtVOCT/kK/xllO2BEDdgyYIlYT7VtVQyP8wqe7an24XmV94eq1wY6zO02d1ZzQ78LvH4YMUThSNUg/ibQmVQvWNNy8O6efEK8c0aVs3LMyYA8lLEHO+yPCEkgO97VEnAGQRiNw7JIz325gG87c/onJbCStyZ3tbkkIo6CzLit+DajqAcJ2rXLk09p2F5dLH1CTvM35OusyfcymtDlknPbFTJUwZv40RbXJr6ndGRSyGW2Phh71bottr0lBgT2akeb9hnJo2ZYONd3CYy0JXgOndsEKry8LdMojPvT9gZrG2fplS1cej/LLLbh/EArpp5Yj+BX8vnja5+CNxHod8HJKPRFCtYahO6avGRbEiJGs8aGRDOGs6SfFnP6lvFQNxz40x7+yh9l5L94ZyNl3fXqlYaUvgQ==
    ND_LASTFM_SECRET: AgAM6VX7aQNw5AkCQHuPnUkJAofaHF+jruRLXd6MZTOTkHBBqZMCBrfTJC3Tww/U3RTuBdBD7yAClK2Kiv44LuqK1fNzu4TWlggy3OY6NAU+JdOOOC2DTIjzr2PgL4wTbKKMJOZczA0OY4PlYbkgE05mT+zUSfOZC/M3o8PNU4u38I/Ac3BUDO8EIKBt2aht8RyEln4IHofOh+Omp5eHNqeM8zHr3Z7tfKGQfBT2+AGGFaz4hA34gZTQnAiO/T8X/pawP6wpcL7z0mx4kqklv69z3Vvj/eTgEu/2vjBsvHK6hls6PxpAAwaK5okhuyZdQi+hlnpa4cJRgTHd3/F1DsOiIMThTd26Y6Y6ajZ8ev09N0Tmi3sX9dTfzLJQftkqDEBEetOeuyGwfsINrvW83jl5se/Yp9aHTCkjIlhKr1U6eRbiRhL3WEQGkCs1Ey5gWpcD5aoTdStkqi7GUgh5kiY5/b5JUBR5SBDOMKSR+iYri2Uez+ddGgozGQ4LhkmC6og+pr8O/3Gy060bkbmGwaKZ0NCmnQ6QBettqcDAEzT3PzwfWA021w+PZfvoiU+ecdiOe0xZGVGRua2NsngTScB5oTke3TdVSBtuvDiZmqgurvKAXU81u8RNrFAbLLmaQ49yPZQJ8fYrMA80OZfKiS6jGo+7QRglAH+JXwub6wWfmCfskBXqEy1HZe95wHyoykZcZabhujUtLUd3UhvSpj3EaUwQNvAMfJM/k64JTyuSBQ==
  template:
    metadata:
      name: navidrome-lastfm
      namespace: navidrome
