---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: navidrome-spotify
  namespace: navidrome
spec:
  encryptedData:
    ND_SPOTIFY_ID: AgCXQcJ6R2HQeKc+QpLnVHKqnFEDfJNRVGtBepSMhdJjjqD4IFPF1ropp0aLycOk9DqpneaMGjfjrN2kLqX+h+kdzffkpuveRJGcqFXhDWqIV0DR974Z6h0HofY95vLXd5mNQjKUz0BrkLVSYMOJ7py/0MzrBnYO8G74bxarl0uhPzhRyaaLo48tVe0+spWmzB5EjASMKI2yAXzABGIEFNJqYbBAsZzbP8Y/F3mr0qO36oKcw6tuoEBGpvzflmA5exL2bjtzsvjDtMmlsqj8hE2vUcPuwkYh09+f/OSASPG2tS5GcD2kJiOmNxMBeaMl1Qyt32HTJHaBShdKQvtNu3mmaWN/dI4aMiX44cxMPsi6mRJhRX4kdOdK4Y4ptYC8mbGLWTALUCMJTKr2TCDdvoKTja1YLaQp1CctqdYEkWwghDlI1aXQgc4gMEkM9IZhErsQ814xvvXGFXIzb2bac6TsVBMpkRo0kG7uXx5qkPRgTM6uwEHtXpGWuHatj4lygCiSJSHnB4jCy9Es6L7VSi+hCxB7dzRj0NeqtOtPP4ZE17N2Oe4d3Hn4VfKorr+wCs9ouzq3O3fpmvGY9vwpnpLj9NQY55Y7ZJqZe2C5yeTlzL6u5LBk5bgfnZcH8fhrAtSEb+8OTzVdCL1GVxk75+GXJ31l+Rvfzi3wE6GZqvaV07RVrDAUL3L/XrAzxTIxhP6icfmPCiYMLD62CNzC49D11oUJ0NiJHwfRrc1BUE6CBQ==
    ND_SPOTIFY_SECRET: AgBlthJLwfF440/woEb1aQ75WKYEWNgWj9H9XlyUZM0IghcNkg10SPCZGF908jJqJUBWRZbpqgslkwljQSzGe99CXU5pTDCE2Aeai1qa1kOF48VE9LU7VNoZZJSMiYkKGABwuMpLhLPxqNoQhSrQXRT8iqkFmiAK/7hKRhWFXttPhRAi8Uwoio8nWsuct75GqOgKYFZ3ly4T+WdzJdE7DunowMXPyWZZku+ofMQkA/CYbGl/Pgief+k04L+umuHr38kcrJw/1CwKarcB0OATrFX2CWluzOfC7JQJSS4rQM5Dgs6LACKPCXkM3HdYOn7HEnAPShA/ZvvFb9+GhFPoHCvizGeIec1KOj/xTVhyosuDuuzGlLEffvLvnGFG9XidEOMxH88oC+u9SIDo2Z/RBBK9tFR7/+QDBuYN2O8+Af/R7Vddxo2u6JLXbWVUg0Xu/0xCiVQVMamMr+V6Hk/P6flnRynAGXQzqyEQ+FJKKejzCjCMsFv71KEKba3+pb3lkMiJuS/YJIC9E+zSshEbn7eVXhn6fln223q9dTpnklHajjP7rUmm4aNUsYcK6I08LNG2gaB53hi4eO/Q/GHq8X+NfvgyeACUbxklmL2Sonef2YWQBoWs26MixHnfZaSJevSydPgcH9wRaYqgylAp6ZU3QyWbB6HxUBkNux2PLa9Kxk5sGj91Vz7T/UWJHdBCL9oQTwFbzb/GhYsBdkxNnFE3w+LwkHDbzEHmA6k+CnfhEw==
  template:
    metadata:
      name: navidrome-spotify
      namespace: navidrome
