apiVersion: v1
kind: ConfigMap
metadata:
  name: beets-config
  namespace: navidrome
data:
  config.yaml: |
    directory: /music
    library: /config/musiclibrary.db
    import:
      move: no
      copy: no
      write: yes
      autotag: no
      log: /config/import.log
    plugins:
      - fetchart
      - embedart
      - lastgenre
    lastgenre:
      count: 1
      prefer_specific: yes
      source: track
      force: yes
      canonical: yes
    fetchart:
      auto: yes
      sources:
        - coverart
        - itunes
        - amazon
        - albumart
      maxwidth: 1000
      cautious: no
    embedart:
      auto: yes
      remove_art_file: yes
