apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache-new
  namespace: jellyfin
  labels:
    app: jellyfin
    media-type: cache
    version: new
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 250Gi
