apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-movies-new
  namespace: jellyfin
  labels:
    app: jellyfin
    media-type: movies
    version: new
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Ti
