apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-movies
  namespace: jellyfin
  annotations:
    # Ensure pvc is created and bound first via longhorn
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: jellyfin
    media-type: movies
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pvc-0fe0801c-4245-4cc3-81b3-03f28556db51
  resources:
    requests:
      storage: 1.5Ti
