apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-tv
  namespace: jellyfin
  annotations:
    # Ensure pvc is created and bound first via longhorn
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: jellyfin
    media-type: tv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Ti
