apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-movies
  namespace: jellyfin
  labels:
    app: jellyfin
    media-type: movies
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
