apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  namespace: jellyfin
  annotations:
    # Ensure pvc is created and bound first via longhorn
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: jellyfin
    media-type: cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pvc-e5c27349-32e2-4ab8-8d9b-7e25bc50e920
  resources:
    requests:
      storage: 500Gi
